FROM node:18 AS builder

WORKDIR /app
COPY package*.json ./

COPY .env .env
COPY . .

RUN npm install --legacy-peer-deps --no-audit --no-fund



RUN npm run build && ls -la /app && echo "Build complete"

FROM nginx:alpine


COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80 
CMD ["nginx", "-g", "daemon off;"]
